import { Lesson } from "@/types/lesson";

export const lessonRPG91: Lesson = {
  id: "rpg-91-build-id-version-stamping",
  title: "Build ID + Version Stamping",
  description: "Print version info at startup. BUILD_ID const, VERSION string, printed in title bar.",
  order: 91,
  xpReward: 100,
  tier: "pro",
  concepts: ["build ID", "version stamping", "release identification", "hs_build_id.h", "ship discipline"],
  part1: {
    title: "Concept: Build ID + Version Stamping",
    type: "concept",
    instructions: `# Build ID + Version Stamping

## Mental Model

Every shipped binary needs an identity. Without a version stamp, you cannot answer the most basic support question: "Which build are they running?" A BUILD_ID and VERSION_STR baked into the binary at compile time give you that answer in one line of output.

This is not optional polish. It is the first thing a professional repo establishes before release. If you cannot tell build 47 from build 48, you cannot triage a bug report.

## What Breaks Without This

\`\`\`cpp
// Player reports: "enemies don't take damage"
// You ask: "which version?"
// Player: "I don't know"
// You: ...
// Bug is already fixed in build 48. Player is on build 45.
// Without version stamping, you cannot even START debugging.
\`\`\`

No version stamp means no triage. No triage means wasted hours chasing already-fixed bugs.

## The Fix: Compile-Time Constants

Define BUILD_ID and VERSION_STR as compile-time constants in a dedicated header. Print them at startup before any game logic runs. The version header is the first thing the player sees and the first thing a log file records.

\`\`\`cpp
const int BUILD_ID = 91;
const char* VERSION_STR = "1.0.0-beta";

void printVersionHeader() {
    cout << "=== HeapSight RPG ===" << endl;
    cout << "Version: " << VERSION_STR << endl;
    cout << "Build:   " << BUILD_ID << endl;
    cout << "===================" << endl;
}
\`\`\`

In a real project, BUILD_ID increments automatically via your build system. For now, we set it manually. The pattern is what matters.

The version header goes in \`hs_build_id.h\` — a single-purpose header that exists solely for release identification. No game logic. No state. Just identity.

## Key Concepts

- **BUILD_ID** — monotonically increasing integer. Every build gets a unique number.
- **VERSION_STR** — human-readable version string following semver (major.minor.patch-label).
- **printVersionHeader()** — called once at startup, prints identity to stdout.
- **Dedicated header** — \`hs_build_id.h\` owns version constants. No other file defines them.

## Performance Insight

Version constants are compile-time values. They cost zero at runtime — the compiler inlines them. The printVersionHeader() call runs exactly once before the game loop starts. Zero impact on tick performance.

## Memory Insight

BUILD_ID lives in the .rodata segment (read-only data). VERSION_STR is a string literal — also .rodata. No heap allocation. No stack cost beyond the function call. These constants exist for the lifetime of the process at zero ongoing cost.

## Beginner Trap

**Hardcoding the version in main():**

\`\`\`cpp
// BAD: version info scattered in main()
int main() {
    cout << "Version 1.0" << endl;  // duplicated? outdated?
}
\`\`\`

When version info is inline in main(), it gets forgotten. Someone updates the build but forgets to change the string. A dedicated header is the single source of truth.

## Elite Insight

Doom shipped with \`__DATE__\` and \`__TIME__\` macros baked into the binary. Every id Software title since then has had a version stamp in the title bar or console output. Unreal Engine generates build IDs automatically via BuildVersion.h. Diablo 2's patch numbers (1.09, 1.10, 1.13c) became part of the game's cultural identity — players still reference them decades later. Your BUILD_ID follows the same pattern.

## Systems Thinking Connection

Version stamping is the RPG equivalent of the Robotics path's \`ros2 node info\` output — both answer "what version of the system is running?" In distributed robotics, node version mismatches cause subtle failures. Same principle applies here.

## Skill Reinforcement

This builds on the constants pattern from Lesson 1 (GRID_W, GRID_H) and feeds into Lesson 95 (Gate C: Zero Warnings) where the build system must produce a clean binary with version metadata, and Lesson 99 (Release Checklist) where the version stamp is part of the pre-release audit.

## Mastery Check

**Q:** Why should BUILD_ID be in a separate header rather than defined in main()?
**A:** A dedicated header is the single source of truth. If version info is in main(), it gets duplicated or forgotten. The header can be auto-generated by the build system, and any file that needs the version can #include it.`,
    starterCode: `#include <iostream>
using namespace std;

// TODO: Define BUILD_ID as const int (set to 91)
// TODO: Define VERSION_STR as const char* (set to "1.0.0-beta")

// TODO: Write printVersionHeader() that prints:
//   === HeapSight RPG ===
//   Version: 1.0.0-beta
//   Build:   91
//   ===================

int main() {
    // TODO: Call printVersionHeader()
    cout << "VERSION_STAMP|ok" << endl;
    return 0;
}`,
    solutionCode: `#include <iostream>
using namespace std;

const int BUILD_ID = 91;
const char* VERSION_STR = "1.0.0-beta";

void printVersionHeader() {
    cout << "=== HeapSight RPG ===" << endl;
    cout << "Version: " << VERSION_STR << endl;
    cout << "Build:   " << BUILD_ID << endl;
    cout << "===================" << endl;
}

int main() {
    printVersionHeader();
    cout << "VERSION_STAMP|ok" << endl;
    return 0;
}`,
    tests: [
      { id: "t1", description: "Version header printed", expectedOutput: "=== HeapSight RPG ===", isPattern: false },
      { id: "t2", description: "Version string shown", expectedOutput: "Version: 1.0.0-beta", isPattern: false },
      { id: "t3", description: "Build ID shown", expectedOutput: "Build:   91", isPattern: false },
      { id: "t4", description: "Stamp confirmation", expectedOutput: "VERSION_STAMP|ok", isPattern: false },
    ],
    hints: [
      "Define two constants at file scope: one int and one const char*.",
      "printVersionHeader() uses cout to print four lines: title, version, build, separator.",
      "const int BUILD_ID = 91; const char* VERSION_STR = \"1.0.0-beta\"; then print them with cout.",
    ],
    estimatedMinutes: 5,
  },
  part2: {
    title: "Build: Version Stamped RPG",
    type: "game_builder",
    instructions: `# Build: Version Stamped RPG

## Mental Model

A shippable binary identifies itself. Your RPG must print its build identity before any game logic runs — this is the first line of every log, every bug report, every screenshot.

## What Breaks Without This

Without version stamping, two players can report the same bug from different builds. You waste hours debugging a phantom issue that was already fixed three builds ago. Version identity is the cheapest insurance in software.

## Your Task

Build a complete version-stamped RPG startup sequence:

1. Define BUILD_ID (91) and VERSION_STR ("1.0.0-beta") as constants
2. Write printVersionHeader() to print the formatted header
3. Initialize a minimal game world (player with HP, one enemy)
4. Run one combat turn and print the result
5. Print BUILD_VERIFIED at the end

**Expected output:**
\`\`\`
=== HeapSight RPG ===
Version: 1.0.0-beta
Build:   91
===================
INIT|player_hp=50|enemy_hp=30
COMBAT|player_attacks|damage=8|enemy_hp=22
BUILD_VERIFIED|id=91|version=1.0.0-beta
\`\`\`

## Performance Insight

The version header runs once at startup. All constants are in .rodata. The game loop is unaffected. This is zero-cost metadata.

## Memory Insight

BUILD_ID and VERSION_STR are compile-time constants stored in read-only memory. They never touch the heap. The printVersionHeader function uses only stack-local cout calls.

## Beginner Trap

**Using a global string variable instead of const char*:**

\`\`\`cpp
string VERSION = "1.0.0-beta";  // BAD: heap allocation at startup
const char* VERSION_STR = "1.0.0-beta";  // GOOD: .rodata, no heap
\`\`\`

std::string allocates heap memory. A const char* literal lives in .rodata — zero allocation.

## Elite Insight

Nintendo's internal build systems stamp every ROM with a build date and revision hash. Carmack's Quake engines print engine version on every startup to stdout. Unity generates ProjectVersion.txt and BuildVersion automatically. Your printVersionHeader() is the same discipline at the smallest possible scale.`,
    starterCode: `#include <iostream>
using namespace std;

// TODO: Define BUILD_ID = 91
// TODO: Define VERSION_STR = "1.0.0-beta"

// TODO: printVersionHeader()

const int MAX_E = 16;
struct WorldState {
    int hp[MAX_E];
    bool alive[MAX_E];
    int entity_count;
};

int main() {
    // TODO: Call printVersionHeader()

    WorldState w = {};
    w.entity_count = 2;
    w.hp[0] = 50; w.alive[0] = true;  // player
    w.hp[1] = 30; w.alive[1] = true;  // enemy
    cout << "INIT|player_hp=" << w.hp[0] << "|enemy_hp=" << w.hp[1] << endl;

    // TODO: Apply 8 damage to enemy, print COMBAT line

    // TODO: Print BUILD_VERIFIED|id=91|version=1.0.0-beta
    return 0;
}`,
    solutionCode: `#include <iostream>
using namespace std;

const int BUILD_ID = 91;
const char* VERSION_STR = "1.0.0-beta";

void printVersionHeader() {
    cout << "=== HeapSight RPG ===" << endl;
    cout << "Version: " << VERSION_STR << endl;
    cout << "Build:   " << BUILD_ID << endl;
    cout << "===================" << endl;
}

const int MAX_E = 16;
struct WorldState {
    int hp[MAX_E];
    bool alive[MAX_E];
    int entity_count;
};

int main() {
    printVersionHeader();

    WorldState w = {};
    w.entity_count = 2;
    w.hp[0] = 50; w.alive[0] = true;
    w.hp[1] = 30; w.alive[1] = true;
    cout << "INIT|player_hp=" << w.hp[0] << "|enemy_hp=" << w.hp[1] << endl;

    int damage = 8;
    w.hp[1] -= damage;
    cout << "COMBAT|player_attacks|damage=" << damage << "|enemy_hp=" << w.hp[1] << endl;

    cout << "BUILD_VERIFIED|id=" << BUILD_ID << "|version=" << VERSION_STR << endl;
    return 0;
}`,
    tests: [
      { id: "g1", description: "Version header printed at startup", expectedOutput: "=== HeapSight RPG ===", isPattern: false },
      { id: "g2", description: "Version string in header", expectedOutput: "Version: 1.0.0-beta", isPattern: false },
      { id: "g3", description: "World initialized", expectedOutput: "INIT|player_hp=50|enemy_hp=30", isPattern: false },
      { id: "g4", description: "Combat turn executed", expectedOutput: "COMBAT|player_attacks|damage=8|enemy_hp=22", isPattern: false },
      { id: "g5", description: "Build verified", expectedOutput: "BUILD_VERIFIED|id=91|version=1.0.0-beta", isPattern: false },
    ],
    hints: [
      "Define the constants at file scope, then write printVersionHeader() to print four lines.",
      "For combat: subtract damage from w.hp[1] and print the result with cout.",
      "BUILD_VERIFIED line: cout << \"BUILD_VERIFIED|id=\" << BUILD_ID << \"|version=\" << VERSION_STR << endl;",
    ],
    estimatedMinutes: 10,
  },
};